### ISSUE TITLE
[Suggestion] Gamepad Assist mode

### ISSUE THREAD

**Issue by Lanselotto** [MgAl2O4/HarpHeroDalamud#1]
it would be very useful to have also gamepad's keys in the Assist panel, even just the name of the keys, like X,Y,RB.

**Comment by MgAl2O4** [comment]
I was afraid someone will request that feature :D
Note assist mode should work already, since it's supposed to just look at note being played. Keybinds - not so much, will play with that.

**Comment by MgAl2O4** [comment]
Added in 1.0.2.0
