### ISSUE TITLE
SimplifyChord removed both notes for two overlapping note

### ISSUE THREAD

**Issue by minstrel271** [MgAl2O4/HarpHeroDalamud#2]
![圖片](https://user-images.githubusercontent.com/7650336/149087141-8898e613-21af-4d17-846b-ac784888dddd.png)
[DebraSolo_Final_Fantasy_XIV_Endwalker_-_Hopeful_Dynamis_P1.zip](https://github.com/MgAl2O4/HarpHeroDalamud/files/7852711/DebraSolo_Final_Fantasy_XIV_Endwalker_-_Hopeful_Dynamis_P1.zip)

**Comment by MgAl2O4** [comment]
Should be fixed in v5.

**Comment by bck6d03** [comment]
我知道這不是issue的正常用法，但我已經沒有更多連絡老朋友的方法了。
minstrel271，我是Dick，如看到這段文字請登入skype。
