### ISSUE TITLE
Xbox gamepad style not detected

### ISSUE THREAD

**Issue by electr0sheep** [MgAl2O4/HarpHeroDalamud#3]
When I have Gamepad Type set to ABXY in the system settings, the inputs still show as playstation.

I'm pretty sure it has to do with this function always returning `1`:
https://github.com/MgAl2O4/HarpHeroDalamud/blob/main/dalamud/utils/InputBindingUtils.cs#L381
when it is called here:
https://github.com/MgAl2O4/HarpHeroDalamud/blob/main/dalamud/utils/InputBindingUtils.cs#L266

My testing indicates that the first function always returns `1`, regardless of what Gamepad Type I set.

I was gonna see if I could figure it out, but I don't really understand that level of reverse engineering! :(

**Comment by MgAl2O4** [comment]
something broke with config options and they can't be accessed in "proper way" now.
added simple hack to retrieve value directly - works on my machine, can you verify if that fixes bug for you?

**Comment by electr0sheep** [comment]
Yep, seems to be working now!
