### ISSUE TITLE
[Feature] MIDI Controller (Key Boards) Assist mode

### ISSUE THREAD

**Issue by dean3c** [MgAl2O4/HarpHeroDalamud#6]
Would it be possible to to have assist mode detect the input of MIDI controllers? For example, using some other Dalamud plugins allows for a MIDI keyboard to be connected to Bard Performance mode. It would be a great training tool if the note detection could interact directly with the MIDI keyboard feedback.

**Comment by MgAl2O4** [comment]
Currently it's supposed to react to "note being played" event in game code, so in theory in should already cover any case of game receiving input data.

Are you asking to add support for midi controller input -> playing notes in game, so it doesn't need other plugins?
Or to recognize correctly inputs sent by another plugin? (what's the name/git repo so i can test against it?)

**Comment by dean3c** [comment]
I've tested it on a wider range of songs. You're right, it is detecting the notes, I think it is more of an issue of I can't toggle/select Half Step on my MIDI keyboard which was making me think it wasn't detecting (I can only switch Octaves).  So ignore that part of my request as I think this is more a physical limitation of my controller (perhaps it would function better with a 61 key controller (mine is only 25) to handle the half steps). 

As to your other question, I've using midiBard with the MIDI INPUT > USB MIDI setting. Could you improve upon their implementation, perhaps. Is it worth your time? Probably not. Thanks for your reply.
